"""
Query planner — parses an incoming query and produces a QueryPlan.

Three responsibilities:
  1. Classify the query into a D1 cognitive category (keyword heuristic, zero LLM calls)
  2. Select a retrieval mode (hybrid | lexical_only | vector_only)
  3. Check index staleness and record warnings on the plan

Keyword vocabulary lives in d1_keywords.toml next to this file.
Edit that file to recalibrate classification; no code change needed.

See docs/agent/plans/v01_phase4_design.md §2 and §7.
"""

from __future__ import annotations

import re
import time
import tomllib
import uuid
from dataclasses import dataclass, field
from pathlib import Path

from cerebra.inspector.event import make_event
from cerebra.inspector.sqlite_log import SQLiteEventLog
from cerebra.storage.db import connect
from cerebra.storage.index_state import is_stale

_KEYWORDS_PATH = Path(__file__).parent / "d1_keywords.toml"

# Regex detecting code-like identifiers: snake_case, camelCase, .extensions,
# "quoted strings", `backtick`, CONSTANT_NAMES, hex literals.
_IDENTIFIER_RE = re.compile(
    r'[a-z]+_[a-zA-Z_]+'           # snake_case (at least one underscore)
    r'|[a-z][a-z]+[A-Z][a-zA-Z]*'  # camelCase (lower then uppercase transition)
    r'|\.[a-zA-Z]{2,6}\b'          # .extension
    r'|"[^"]{2,}"'                  # "quoted string" (2+ chars)
    r'|`[^`]+`'                     # `backtick block`
    r'|[A-Z]{2,}_[A-Z_]+'           # CONSTANT_NAME
)

_keywords_cache: dict[int, list[str]] | None = None


def _load_keywords() -> dict[int, list[str]]:
    """Load and cache the D1 keyword vocabulary from d1_keywords.toml."""
    global _keywords_cache
    if _keywords_cache is None:
        with open(_KEYWORDS_PATH, "rb") as f:
            data = tomllib.load(f)
        _keywords_cache = {
            int(k, 16): [kw.lower() for kw in v]
            for k, v in data["d1"].items()
        }
    return _keywords_cache


@dataclass
class QueryPlan:
    """Parsed interpretation of an incoming query.

    Generated by query_plan(); consumed by run_traversal() and score_candidates().
    trace_id is generated at plan time so inspector events across the pipeline
    share a consistent subject_id before the trace row is written to the DB.
    """

    trace_id: str                 # stable ID for this query's lifecycle (uuid)
    raw_query: str
    query_d1: int | None          # inferred D1 hex digit, None if unclassifiable
    query_d1_d2_d3: str | None    # hex pattern string e.g. "0x5" (D1 only in Phase 4)
    mode: str                     # "hybrid" | "lexical_only" | "vector_only"
    max_candidates: int           # cap for traversal Step 5 vector fallback
    staleness_warnings: list[str] = field(default_factory=list)


def _classify_d1(query: str) -> int | None:
    """Classify a query into a D1 cognitive category by keyword vocabulary.

    Returns the D1 hex value (int 0–15) of the best-matching category, or
    None if no keywords match. Ties are broken by earliest keyword position
    in the query string.
    """
    keywords = _load_keywords()
    query_lower = query.lower()
    query_tokens = set(re.split(r'\W+', query_lower))
    query_tokens.discard("")

    hits: dict[int, int] = {}
    for d1_int, kw_list in keywords.items():
        count = 0
        for kw in kw_list:
            if " " in kw:
                if kw in query_lower:
                    count += 1
            elif kw in query_tokens:
                count += 1
        if count > 0:
            hits[d1_int] = count

    if not hits:
        return None

    max_count = max(hits.values())
    candidates = [d1 for d1, c in hits.items() if c == max_count]

    if len(candidates) == 1:
        return candidates[0]

    # Tie-break: return the category whose first matching keyword appears earliest
    def _first_hit_pos(d1: int) -> int:
        for kw in keywords[d1]:
            pos = query_lower.find(kw)
            if pos != -1:
                return pos
        return 99_999

    return min(candidates, key=_first_hit_pos)


def _looks_like_identifier_query(query: str) -> bool:
    """True if the query contains code identifiers, filenames, or quoted strings."""
    return bool(_IDENTIFIER_RE.search(query))


def _detect_mode(query: str, query_d1: int | None) -> str:
    """Select retrieval mode from query characteristics.

    lexical_only  — query contains code identifiers / filenames / quoted strings.
    vector_only   — 1-2 word query with no D1 keyword hit (too short for heuristic).
    hybrid        — all other cases; runs full six-step traversal.
    """
    if _looks_like_identifier_query(query):
        return "lexical_only"
    if len(query.split()) <= 2 and query_d1 is None:
        return "vector_only"
    return "hybrid"


def _check_staleness(db_path: Path) -> list[str]:
    """Check lexical, vector, and graph indexes for staleness.

    Checks both the never-built condition (last_updated_at == 0 via is_stale())
    and index-specific drift detectors for lexical and vector.
    Graph has no drift detector in Phase 4.

    Returns list of human-readable warning strings (empty = all fresh).
    """
    warnings: list[str] = []

    # ── Lexical ──────────────────────────────────────────────────────────────
    if is_stale(db_path, "lexical"):
        warnings.append("lexical index never built (last_updated_at=0)")
    else:
        # Drift: any active record created after last FTS build?
        # Lazy import avoids circular dependency (lexical imports index_state)
        from cerebra.storage.lexical import is_lexical_stale
        if is_lexical_stale(db_path):
            warnings.append("lexical index may be stale: new records since last build")

    # ── Vector ───────────────────────────────────────────────────────────────
    if is_stale(db_path, "vector"):
        warnings.append("vector index never built (last_updated_at=0)")
    else:
        with connect(db_path) as conn:
            pending: int = conn.execute(
                "SELECT COUNT(*) FROM pending_embeddings"
            ).fetchone()[0]
        if pending > 0:
            warnings.append(
                f"vector index may be stale: {pending} records pending embedding"
            )

    # ── Graph (no drift detector in Phase 4) ─────────────────────────────────
    if is_stale(db_path, "graph"):
        warnings.append("graph index never built (last_updated_at=0)")

    return warnings


def query_plan(
    query: str,
    db_path: Path,
    *,
    max_candidates: int = 200,
    event_log: SQLiteEventLog | None = None,
) -> QueryPlan:
    """Parse a query and produce a QueryPlan for the traversal.

    Emits QueryReceived and QueryPlanned inspector events when event_log provided.
    """
    trace_id = f"trace_{uuid.uuid4().hex[:12]}"

    if event_log is not None:
        event_log.write(make_event(
            event_type="QueryReceived",
            actor="retrieval",
            summary=f"Query received: '{query[:60]}'",
            data={"query": query, "vault_path": str(db_path)},
            subject_id=trace_id,
        ))

    query_d1 = _classify_d1(query)
    mode = _detect_mode(query, query_d1)
    query_d1_d2_d3 = f"0x{query_d1:x}" if query_d1 is not None else None
    staleness_warnings = _check_staleness(db_path)

    plan = QueryPlan(
        trace_id=trace_id,
        raw_query=query,
        query_d1=query_d1,
        query_d1_d2_d3=query_d1_d2_d3,
        mode=mode,
        max_candidates=max_candidates,
        staleness_warnings=staleness_warnings,
    )

    if event_log is not None:
        event_log.write(make_event(
            event_type="QueryPlanned",
            actor="retrieval.planner",
            summary=f"Query planned: mode={mode}, D1={query_d1_d2_d3}",
            data={
                "trace_id": trace_id,
                "query_sku_d1": query_d1,
                "query_sku_pattern": query_d1_d2_d3,
                "mode": mode,
                "staleness_warnings": staleness_warnings,
            },
            subject_id=trace_id,
        ))

    return plan
